services:
  - type: web
    name: skyink
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gui_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
